[package]
name = "authly"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
bit-set = "0.8"
rocksdb = { version = "0.22", default-features = false }
tracing = "0.1"
unsigned-varint = "0.8"

[dev-dependencies]
