services:
  authly-pal:
    image: protojour/authly-pal:dev
    environment:
      DANGER_ENCRYPTION_DISABLED: 'true'

  authly:
    image: situ/authly:dev
    environment:
      AUTHLY_HOSTNAME: authly
      AUTHLY_K8S: 'false'
      AUTHLY_CLUSTER_API_SECRET: ifyougetholdofthisclassifiedpieceofinformationiwillunfortunatelyhavetokillyou
      AUTHLY_CLUSTER_RAFT_SECRET: donttellanybodyabouttheverysecretstring
      AUTHLY_EXPORT_TLS_TO_ETC: 'true'
      AUTHLY_PAL_URL: http://authly-pal:6666
    ports:
      - 1443:443
    volumes:
      - authly-data:/var/lib/authly/data
      - authly-local-ca:/etc/authly/local
      - testservice-identity:/etc/authly/service/f3e799137c034e1eb4cd3e4f65705932
      - ../../.local/etc/cluster:/etc/authly/cluster:ro
      - ../../examples:/etc/authly/documents:ro
    command: serve

  testservice:
    image: situ/authly-testservice:dev
    volumes:
      - authly-local-ca:/etc/authly/local:ro
      - testservice-identity:/etc/authly/identity:ro

volumes:
  authly-data:
  authly-local-ca:
  testservice-identity:
