# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "clippy-all"

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets", "--color", "always"]
need_stdout = false

# This job lets you run
# - all tests: bacon test
# - a specific test: bacon test -- config::test_default_files
# - the tests of a package: bacon test -- -- -p config
[jobs.test]
command = [
    "cargo",
    "test",
    "--color",
    "always",
    "--",
    "--color",
    "always",  # see https://github.com/Canop/bacon/issues/124
]
need_stdout = true

# Run authly-webdev
[jobs.webdev]
command = ["cargo", "run", "--color", "always", "-p", "authly-webdev"]
need_stdout = true
allow_warnings = true
background = true
on_change_strategy = "kill_then_restart"

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal global prefs.toml file instead.
[keybindings]
c = "job:clippy-all"
w = "job:webdev"
