# This docker-compose file is used for local development.

services:
  authly-pal:
    image: protojour/authly-pal:dev
    environment:
      DANGER_ENCRYPTION_DISABLED: 'true'
    ports:
      - 6666:6666
