global:
  # -- The namespace to deploy to. Defaults to the `helm` installation namespace.
  namespace: ""

# Authly cluster-related values
cluster:
  # How many replicas to run
  replicas: 1

# The Authly container image to use
image:
  repository: protojour/authly
  tag: ""
  pullPolicy: IfNotPresent

# Control how startup documents are provided to Authly
documents:
  # Whether the Chart should create an empty `authly-documents` ConfigMap.
  # If this is set to false, this resource will not be controlled by Helm,
  # and must be created manually. The Authly application will not be able
  # to start without it.
  createConfigMap: true

  # A map of key (filename) - value (file contents) documents
  files: {}

serviceAccount:
  # Whether to create service account
  create: true

  # Service account name, defaults to fullname
  name: ""

persistentVolume:
  # How much space to allocate on persistent volume
  size: 256Mi

pod:
  # Extra labels to put on Authly pods
  extraLabels: {}
