apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: authly-test
  name: arx
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-gateway-api
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - referencegrants
  - grpcroutes
  verbs: ["list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-gateway-api-binding
subjects:
- kind: ServiceAccount
  namespace: authly-test
  name: arx
roleRef:
  kind: ClusterRole
  name: read-gateway-api
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: arx
spec:
  controllerName: "situ.net/arx"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  namespace: authly-test
  name: arx
spec:
  gatewayClassName: arx
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: v1
kind: Service
metadata:
  namespace: authly-test
  name: arx
spec:
  # Setting up the gateway at loadbalancer:
  type: LoadBalancer
  selector:
    app: arx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arx
  namespace: authly-test
  labels:
    app: arx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arx
  template:
    metadata:
      labels:
        app: arx
        authlyDev: restart
    spec:
      serviceAccountName: arx
      enableServiceLinks: false
      containers:
      - name: arx
        image: protojour/arx:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: authly-certs
            mountPath: /etc/authly/certs
      volumes:
        - name: authly-certs
          configMap:
            name: authly-certs.crt
