[package]
name = "authly-policy"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
tracing = "0.1"
unsigned-varint = "0.8"

[dev-dependencies]
