[authly-document]
id = "bc9ce588-50c3-47d1-94c1-f88b21eaf299"

[[service]]
eid = "272878235402143010663560859986869906352"
label = "testservice"
kubernetes = { service-account = [
    { namespace = "authly-test", name = "testservice" },
] }

[[entity-property]]
service = "testservice"
label = "role"
attributes = ["ui:user", "ui:admin"]

[[resource-property]]
service = "testservice"
label = "name"
attributes = ["ontology", "storage"]

[[resource-property]]
service = "testservice"
label = "ontology:action"
attributes = ["read", "deploy", "stop"]

[[resource-property]]
service = "testservice"
label = "buckets:action"
attributes = ["read"]

[[resource-property]]
service = "testservice"
label = "bucket:action"
attributes = ["read", "create", "delete"]

[[resource-property]]
service = "testservice"
label = "object:action"
attributes = ["read", "create", "delete"]

[[policy]]
service = "testservice"
label = "allow for main service"
allow = "Subject.entity == testservice"

[[policy]]
service = "testservice"
label = "allow for UI user"
allow = "Subject.role contains role/ui:user"

[[policy]]
service = "testservice"
label = "allow for UI admin"
allow = "Subject.role contains role/ui:admin"

[[policy-binding]]
service = "testservice"
attributes = ["ontology:action/read"]
policies = ["allow for main service", "allow for UI user"]

[[policy-binding]]
service = "testservice"
attributes = ["ontology:action/deploy"]
policies = ["allow for main service", "allow for UI admin"]
