[package]
name = "authly-test"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
anyhow = "1"
axum = "0.7"
reqwest = { version = "0.12", default-features = false, features = ["http2", "json", "rustls-tls"] }
rcgen = "0.13"
rustls = "0.23"
serde_json = "1"
time = "0.3"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
tokio-util = "0.7"
tower-server = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "fmt",
    "ansi",
] }

[dev-dependencies]
