[authly-document]
id = "d783648f-e6ac-4492-87f7-43d5e5805d60"

[[entity]]
eid = "p.0fbcd73e1a884424a1615c3c3fdeebec"
label = "me"
email = ["me@mail.com"]
username = "testuser"
password-hash = [
    "$argon2id$v=19$m=19456,t=2,p=1$/lj8Yj6ZTJLiqgpYb4Nn0g$z79FFMXstrkY8KmpC0vQWIDcne0lylBbctUAluIVqLk",
]

[[entity]]
eid = "g.81dc1da0fa644142bad35043a9c3b025"
label = "us"

[[entity]]
eid = "p.96bf83f88cbf455fa356553f7fca1b9e"
label = "you"

[[members]]
entity = "us"
members = ["me", "you"]
