[authly-document]
id = "bc9ce588-50c3-47d1-94c1-f88b21eaf299"

[[service-entity]]
eid = "e.f3e799137c034e1eb4cd3e4f65705932"
label = "testservice"
attributes = ["authly:role:authenticate", "authly:role:get_access_token"]
kubernetes-account = { name = "testservice", namespace = "authly-test" }

[[entity-property]]
domain = "testservice"
label = "role"
attributes = ["ui/user", "ui/admin"]

[[entity-attribute-binding]]
eid = "e.0fbcd73e1a884424a1615c3c3fdeebec"
attributes = ["testservice:role:ui/user"]

[[entity-attribute-binding]]
eid = "e.96bf83f88cbf455fa356553f7fca1b9e"
attributes = ["testservice:role:ui/admin"]

[[resource-property]]
domain = "testservice"
label = "name"
attributes = ["ontology", "storage"]

[[resource-property]]
domain = "testservice"
label = "ontology/action"
attributes = ["read", "deploy", "stop"]

[[resource-property]]
domain = "testservice"
label = "buckets/action"
attributes = ["read"]

[[resource-property]]
domain = "testservice"
label = "bucket/action"
attributes = ["read", "create", "delete"]

[[resource-property]]
domain = "testservice"
label = "object/action"
attributes = ["read", "create", "delete"]

[[policy]]
label = "allow for main service"
allow = "Subject.authly:entity == testservice"

[[policy]]
label = "allow for UI user"
allow = "Subject.testservice:role contains testservice:role:ui/user"

[[policy]]
label = "allow for UI admin"
allow = "Subject.testservice:role contains testservice:role:ui/admin"

[[policy-binding]]
attributes = ["testservice:ontology/action:read"]
policies = ["allow for main service", "allow for UI user"]

[[policy-binding]]
attributes = ["testservice:ontology/action:deploy"]
policies = ["allow for main service", "allow for UI admin"]
