# Basic configuration environment variables:
{{ $cfgName := print (include "authly.name" .) "-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "authly.namespace" . }}
  name: {{ $cfgName }}
data:
  {{ $configmap := (lookup "v1" "ConfigMap" .Release.Namespace $cfgName) | default dict }}
  {{ $data := (get $configmap "data") | default dict }}
  {{ $authlyId := (get $data "AUTHLY_ID") | default (include "authly.randHex" 64) }}
  AUTHLY_ID: {{ $authlyId }}
  AUTHLY_LOG: info
  AUTHLY_K8S: "true"
  AUTHLY_K8S_STATEFULSET: {{ .Release.Name }}
  AUTHLY_K8S_HEADLESS_SVC: {{ include "authly.fullname" . }}-cluster
  AUTHLY_K8S_AUTH_HOSTNAME: {{ include "authly.fullname" . }}-k8s
  AUTHLY_K8S_AUTH_SERVER_PORT: "2443"
  {{ if .Values.secrets.baoUrl }}
  AUTHLY_BAO_URL: {{ .Values.secrets.baoUrl }}
  {{ end }}
---
# Secrets for the Authly cluster:
{{ $secretName := print (include "authly.name" .) "-secrets" }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "authly.namespace" . }}
  name: {{ $secretName }}
stringData:
  {{ $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{ $stringData := (get $secret "stringData") | default dict }}
  {{ $apiSecret := (get $stringData "AUTHLY_CLUSTER_API_SECRET") | default (randAlphaNum 32 | b64enc) }}
  {{ $raftSecret := (get $stringData "AUTHLY_CLUSTER_RAFT_SECRET") | default (randAlphaNum 32 | b64enc) }}
  AUTHLY_CLUSTER_API_SECRET: {{ $apiSecret | quote }}
  AUTHLY_CLUSTER_RAFT_SECRET: {{ $raftSecret | quote }}
