{{- if  .Values.documents.createConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "authly.namespace" . }}
  name: {{ include "authly.name" . }}-documents
data:
{{- toYaml .Values.documents.files | nindent 2 -}}
{{- end }}
