# Helm values for Authly in development/demo mode
image:
  tag: dev
  pullPolicy: Always

pod:
  extraLabels:
    authlyDev: restart

documents:
  # The documents ConfigMap is created in Justfile
  createConfigMap: false
