apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: authly-test
  name: testservice
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: authly-test
  name: testservice
spec:
  selector:
    app: testservice
  ports:
  - name: web
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: authly-test
  name: testservice
  labels:
    app: testservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testservice
  template:
    metadata:
      labels:
        app: testservice
    spec:
      serviceAccountName: testservice
      enableServiceLinks: false
      containers:
      - name: testservice
        image: situ/authly-testservice:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: authly-ca
            mountPath: /etc/authly/local
      volumes:
        - name: authly-ca
          configMap:
            name: authly-local-ca.crt
